INSERT INTO USER_CATEGORY (CODE, DAILY_DEBIT_LIMIT, WEEKLY_DEBIT_LIMIT, MONTHLY_DEBIT_LIMIT
, DAILY_CREDIT_LIMIT, WEEKLY_CREDIT_LIMIT, MONTHLY_CREDIT_LIMIT)
VALUES ('VIP','20000','50000', '100000', '15000', '25000', '60000');

INSERT INTO USER_CATEGORY (CODE, DAILY_DEBIT_LIMIT, WEEKLY_DEBIT_LIMIT, MONTHLY_DEBIT_LIMIT
, DAILY_CREDIT_LIMIT, WEEKLY_CREDIT_LIMIT, MONTHLY_CREDIT_LIMIT)
VALUES ('NORM','10000','30000', '50000', '10000', '15000', '40000');

--INSERT INTO Authority (ID, CODE, DESCRIPTION)
--VALUES (1, 'VIEW_USERS','View users list');
--
--INSERT INTO Authority (ID, CODE, DESCRIPTION)
--VALUES (2, 'CREATE_ACCOUNT','Create new account');

--INSERT INTO ACCOUNT_STATUS (ID, CODE, DESCRIPTION)
--VALUES (1, 'Active','Active');
--
--INSERT INTO ACCOUNT_STATUS (ID, CODE, DESCRIPTION)
--VALUES (2, 'Suspend','Suspend');
--
--INSERT INTO ACCOUNT_STATUS (ID, CODE, DESCRIPTION)
--VALUES (3, 'Pending','Pending');
--
--INSERT INTO ACCOUNT_STATUS (ID, CODE, DESCRIPTION)
--VALUES (4, 'Stolen','Stolen');
--
--INSERT INTO ACCOUNT_STATUS (ID, CODE, DESCRIPTION)
--VALUES (5, 'Dormant','Dormant');